# Generated by Django 4.0 on 2021-12-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_publicado_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='Borrador'),
        ),
    ]
